version: '3.8'

services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - server
    environment:
      - NODE_ENV=production

  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/autoscriber

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=autoscriber
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
