const fs = require("fs");
const path = require("path");

// Path to the gql.ts file generated by graphql-codegen
const filePath = path.join(__dirname, "../client/src/gql/gql.ts");

// Read the file into memory
fs.readFile(filePath, "utf8", function (err, data) {
  if (err) {
    console.error("An error occurred while reading the file:", err);
    return;
  }

  // Find the line that has "const documents = [];"
  const search = "const documents = [];";

  // Replace it with a strongly typed version
  const replace = "const documents: any[] = [];";

  // Replace in content
  const updatedData = data.replace(search, replace);

  // Write the updated content back to the file
  fs.writeFile(filePath, updatedData, "utf8", function (err) {
    if (err) {
      console.error("An error occurred while writing the file:", err);
    } else {
      console.log("Successfully updated gql.ts");
    }
  });
});
